name: flutter_wallet
description: Flutter plugin to add pkpass to iOS wallet (Passbook)
version: 0.0.4

environment:
#  sdk: ">=2.1.0 <3.0.0"
  sdk: ">=3.4.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.vicoaguado.flutter_wallet
    pluginClass: FlutterWalletPlugin
